paths:
  cache: ./data
  output: ./output
  progress: ./data/.progress.yaml
  manifest: ./data/.shards.txt

processing:
  prefetch_shards: 4
  delete_completed_shards: true

output:
  image:
    height: 256
    width: 256
    pad: none # none | edge | white | black | transparent
    format: webp # png | jpg | webp
    quality: 95

filter:
  include_tags: []
  exclude_tags: []

face_detection:
  device: auto # auto | cpu | cuda | mps
  confidence_threshold: 0.8

resume:
  enabled: false
  last_completed_shard: data_1/shard-000045.tar
