[project]
name = "danbooru-face-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cheesechaser>=0.2.2",
    "dghs-imgutils>=0.19.0",
    "duckdb>=1.5.3",
    "huggingface-hub>=1.12.2",
    "onnxruntime>=1.26.0",
    "pillow>=12.2.0",
    "pyyaml>=6.0.3",
]

[project.scripts]
danbooru-face-parser = "processor:main"
